version: "3.8"
services:
  frontend-auth:
    container_name: frontend-auth
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-frontendauth
      args:
        client_id: "1"
        client_secret: ""
    ports:
      - "3002:80"
    networks:
      - blitzvideo-api_default

networks:
  blitzvideo-api_default:
    external: true

